// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq2wVzopoN8_A02_hzkM5wDq6vuvZEhU4',
    appId: '1:270103178157:web:3986e438382b19f0f58f24',
    messagingSenderId: '270103178157',
    projectId: 'dompetku-2d66c',
    authDomain: 'dompetku-2d66c.firebaseapp.com',
    storageBucket: 'dompetku-2d66c.firebasestorage.app',
    measurementId: 'G-0CZW2GPK2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRaziVzGtzMR2qBdI2gtdv0dlt6_pbjg',
    appId: '1:270103178157:android:ebd64feb785ab8dcf58f24',
    messagingSenderId: '270103178157',
    projectId: 'dompetku-2d66c',
    storageBucket: 'dompetku-2d66c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUX7DoRECKBbBLsiCQGOe5sP73couSGOU',
    appId: '1:270103178157:ios:1ef1bb062db88be4f58f24',
    messagingSenderId: '270103178157',
    projectId: 'dompetku-2d66c',
    storageBucket: 'dompetku-2d66c.firebasestorage.app',
    iosBundleId: 'com.example.dompetku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUX7DoRECKBbBLsiCQGOe5sP73couSGOU',
    appId: '1:270103178157:ios:1ef1bb062db88be4f58f24',
    messagingSenderId: '270103178157',
    projectId: 'dompetku-2d66c',
    storageBucket: 'dompetku-2d66c.firebasestorage.app',
    iosBundleId: 'com.example.dompetku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq2wVzopoN8_A02_hzkM5wDq6vuvZEhU4',
    appId: '1:270103178157:web:8e0d2082a4d86f28f58f24',
    messagingSenderId: '270103178157',
    projectId: 'dompetku-2d66c',
    authDomain: 'dompetku-2d66c.firebaseapp.com',
    storageBucket: 'dompetku-2d66c.firebasestorage.app',
    measurementId: 'G-7G8VKVVPFF',
  );
}
